server:
  port: 8888

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:

      #权重路由
      - id: service1_v1
        uri: http://localhost:10001/getServices
        predicates:
        - Path=/test
        - Weight=test1, 5

      - id: service1_v2
        uri: http://localhost:10002/getServices
        predicates:
        - Path=/test
        - Weight=test1, 95
    #  - id: default_path_to_http
        #uri: http://baidu.com:80/
        #order: 10000
      #  predicates:
        #- Path=/customer/**
        #- After=2018-03-18T17:32:58.129+08:00[Asia/Shanghai]   #After断言
        #- Before=2022-03-13T00:54:30.877+08:00[Asia/Shanghai]  #before断言

      #  filters:
       # - SetPath=/
      #  - StripPrefix=1  #去掉前缀
       # - AddResponseHeader=X-Response-Default-Foo, Default-Bar

eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


#Metrics 系统负载的动态限流
management:
  endpoints:
    web:
      exposures:
        include: /*




